'use strict';
const $=s=>document.querySelector(s);let state=null,currentSlug='',dirty=false;
function status(text,error=false){$('#editor-status').textContent=text;$('#editor-status').classList.toggle('error',error)}
async function api(path,data){const response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Editor-Token':window.EDITOR_TOKEN}:{},body:data?JSON.stringify(data):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||'请求失败');return result}
async function load(){state=await api('/api/state');const keepCategory=$('#p-category').value;$('#p-category').replaceChildren();for(const c of state.config.categories){const option=document.createElement('option');option.value=c.id;option.textContent=c.name;$('#p-category').append(option)}if(state.config.categories.some(c=>c.id===keepCategory))$('#p-category').value=keepCategory;renderList()}
function renderList(){const query=$('#post-search').value.toLowerCase();$('#post-list').replaceChildren();for(const p of state.posts.filter(p=>(p.title+p.slug).toLowerCase().includes(query))){const b=document.createElement('button');b.type='button';b.className='post-select'+(p.slug===currentSlug?' active':'');const t=document.createElement('strong');t.textContent=p.title;const d=document.createElement('small');d.textContent=p.date+' · '+(p.draft?'草稿':'已发布');b.append(t,d);b.addEventListener('click',()=>{if(!dirty||confirm('当前修改尚未保存。放弃修改并切换？'))openPost(p)});$('#post-list').append(b)}}
function openPost(p=null){dirty=false;$('#post-form').hidden=false;$('#config-form').hidden=true;currentSlug=p?.slug||'';$('#form-title').textContent=p?'编辑文章':'新建文章';$('#delete-post').hidden=!p;for(const key of ['title','slug','category','date','summary','body'])$('#p-'+key).value=p?.[key]||(key==='date'?new Date().toLocaleDateString('en-CA'):key==='category'?state.config.categories[0].id:'');$('#p-slug').readOnly=!!p;$('#p-tags').value=(p?.tags||[]).join(', ');for(const key of ['pinned','featured','draft'])$('#p-'+key).checked=!!p?.[key];renderList();status('')}
const configLabels={name:'网站名称',tagline:'副标题',author:'作者 / 站长',domain:'正式域名（含 https://，不带路径）',hero_title:'首页主标题（第一行）',hero_accent:'首页强调标题（第二行）',description:'首页介绍与默认搜索摘要',about:'关于我',email:'联系邮箱（公开展示，选填）',wechat:'微信（公开展示，选填）',github:'GitHub 或公开主页 URL（选填）',icp:'真实 ICP 备案号（没有则留空）',police_record:'真实公安备案号（没有则留空）',police_url:'公安备案查询链接（选填）'};
function openSettings(){dirty=false;$('#post-form').hidden=true;$('#config-form').hidden=false;$('#config-fields').replaceChildren();for(const [key,label]of Object.entries(configLabels)){const wrap=document.createElement('label');wrap.className='field';wrap.textContent=label;const input=document.createElement(['about','description'].includes(key)?'textarea':'input');input.id='c-'+key;input.value=state.config[key]||'';if(key==='domain')input.type='url';if(key==='email')input.type='email';if(['name','author','domain','hero_title','hero_accent'].includes(key))input.required=true;wrap.append(input);$('#config-fields').append(wrap)}$('#c-demo').checked=state.config.demo;status('')}
$('#new-post').addEventListener('click',()=>{if(!dirty||confirm('放弃尚未保存的修改？'))openPost()});$('#settings').addEventListener('click',()=>{if(!dirty||confirm('放弃尚未保存的修改？'))openSettings()});$('#post-search').addEventListener('input',renderList);
for(const form of [$('#post-form'),$('#config-form')])form.addEventListener('input',()=>dirty=true);
async function save(path,data){const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);status('正在保存并重新生成网站…');try{const result=await api(path,data);dirty=false;await load();status(`保存成功，已生成 ${result.build.pages} 个页面。刷新预览窗口即可查看。`);return true}catch(error){status(error.message,true);return false}finally{buttons.forEach(b=>b.disabled=false)}}
$('#post-form').addEventListener('submit',async e=>{e.preventDefault();const data={originalSlug:currentSlug};for(const key of ['title','slug','category','date','summary','body'])data[key]=$('#p-'+key).value;for(const key of ['pinned','featured','draft'])data[key]=$('#p-'+key).checked;data.tags=$('#p-tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean);if(await save('/api/post',data)){currentSlug=data.slug;$('#p-slug').readOnly=true;$('#delete-post').hidden=false;$('#form-title').textContent='编辑文章';renderList()}});
$('#config-form').addEventListener('submit',async e=>{e.preventDefault();const data={demo:$('#c-demo').checked};for(const key of Object.keys(configLabels))data[key]=$('#c-'+key).value;await save('/api/config',data)});
$('#delete-post').addEventListener('click',async()=>{if(!currentSlug||!confirm('确定删除这篇文章？对应源文件也会删除，请先做好备份。'))return;if(await save('/api/delete',{slug:currentSlug})){openPost();status('文章已删除，网站已重新生成。')}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
load().then(()=>openPost(state.posts[0]||null)).catch(error=>status('无法连接本地工作台：'+error.message,true));
